"""creat table authors

Revision ID: c1e18e94ccb1
Revises: c616da7f46c6
Create Date: 2025-01-17 22:41:22.188859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1e18e94ccb1"
down_revision: Union[str, None] = "c616da7f46c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("biography", sa.String(), nullable=True),
        sa.Column("date_birth", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authors_full_name"), "authors", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_authors_id"), "authors", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_authors_id"), table_name="authors")
    op.drop_index(op.f("ix_authors_full_name"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
