"""creat table genre

Revision ID: b802698d7b24
Revises: c1e18e94ccb1
Create Date: 2025-01-18 11:44:31.970998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b802698d7b24"
down_revision: Union[str, None] = "c1e18e94ccb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genre_id"), "genre", ["id"], unique=False)
    op.create_index(op.f("ix_genre_title"), "genre", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_genre_title"), table_name="genre")
    op.drop_index(op.f("ix_genre_id"), table_name="genre")
    op.drop_table("genre")
    # ### end Alembic commands ###
